# Example root argo app manifest.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/oguzhan-yilmaz/keycloak-gitops'
    targetRevision: master
    # path to the directory containing the application manifests
    path: apps/
    directory:
      recurse: true # finds all yaml files in subdirectories
      include: '{*.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true